server:
  port: 8050
# 应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: DEFAULT_GROUP # 进一步细分
        weight: 1 # 权重，结合负载均衡设置
# springboot默认的日志级别是info，feign的dubug日志级别就不会输入
logging:
  level:
    com.liuyd.order.feign: debug
# feign日志局部配置
feign:
  client:
    config:
      product-service:
        loggerLevel: BASIC
        contract: feign.Contract.Default # 设置默认的契约 还原成原生的feign
        connectTimeout: 5000 # 连接超时
        readTimeout: 10000